## Homework
+ Pre-requisite: You need to install Python, NumPy, Pandas, Matplotlib and Seaborn. For that, you can use the instructions from <A Href="https://github.com/DataTalksClub/machine-learning-zoomcamp/blob/master/01-intro/06-environment.md">06-environment.md.</A>

### Q1. Pandas version

In [1]:
import pandas as pd
pd.__version__

'2.2.2'

+ The version of installed pandas version is **2.2.2**

### Q2. Record Counts
+ Download data <A Href="https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv">here.</A>

How many records are in the dataset?
+ 12
+ 1000
+ 2160
+ 12160

There are 2160 records.

In [2]:
# read the data
data = pd.read_csv(r"C:\Users\user\Machine_Learning_ZoomCamp\Introduction to Machine Learning\data\laptops.csv")
data.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [3]:
print(f"The dataset has {data.shape[0]} records")

The dataset has 2160 records


### Q3. Laptop Brands
How many laptop brands are present in the dataset?
+ 12
+ 27
+ 28
+ 2160

There are 27 laptop brands.

In [4]:
laptop_brands = data['Brand'].nunique()
print(f"There are {laptop_brands} laptop brands.")

There are 27 laptop brands.


### Q4. Missing values
How many columns in the dataset have missing values?

+ 0
+ 1
+ 2
+ 3

In [5]:
number_col_missing = data.isnull().sum()
number_col_missing

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

**3** columns that is **Storage type**, **GPU**, and **Screen** have missing values.

### Q5. Maximum final price
What's the maximum final price of Dell notebooks in the dataset?

+ 869
+ 3691
+ 3849
+ 3936

In [17]:
dell_notebooks = data[data['Brand'] == 'Dell']
maximum_price = dell_notebooks['Final Price'].max()
print(maximum_price)

3936.0


### Q6. Median value of Screen
1. Find the median value of Screen column in the dataset.
2. Next, calculate the most frequent value of the same Screen column.
3. Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.
4. Now, calculate the median value of Screen once again.
   
Has it changed?
+ **No**

In [6]:
data.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [7]:
# Median value of Screen column
data = data.copy()
med_value_screen = data['Screen'].median()
most_frequent_value_screen = data['Screen'].mode()

print(f"The median value of Screen size is {med_value_screen}.")
print(f"The most frequent value of Screen size is {most_frequent_value_screen}.")
data.fillna({"Screen": 0}, inplace=True)
data.isnull().sum()
print(f"After filling missing values with zero in screen column, the median screen size is now {data['Screen'].median()}\n")
print(f"The median value has not changed")

The median value of Screen size is 15.6.
The most frequent value of Screen size is 0    15.6
Name: Screen, dtype: float64.
After filling missing values with zero in screen column, the median screen size is now 15.6

The median value has not changed


### Q7. Sum of weights
1. Select all the "Innjoo" laptops from the dataset.
2. Select only columns RAM, Storage, Screen.
3. Get the underlying NumPy array. Let's call it X.
4. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
5. Compute the inverse of XTX.
6. Create an array y with values [1100, 1300, 800, 900, 1000, 1100].
7. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
8. What's the sum of all the elements of the result?

In [8]:
# Selecting all the "Innjoo" laptops from the dataset
innjoo_laptops = data[data['Brand'] == 'Innjoo']
innjoo_laptops

Laptop Status   Brand Model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1483  Innjoo Voom Pro Intel Celeron N3350/6GB/128GB ...    New  Innjoo  Voom   

                CPU  RAM  Storage Storage type  GPU  Screen Touch  Final Price  
1478  Intel Celeron    8      256          SSD  NaN    15.6    No       311.37  
1479  Intel Celeron    8      512          SSD  NaN    15.6    No       392.55  
1480  Intel Celeron    4       64         eMMC  NaN    14.1    No       251.40  
1481  Intel Celeron    6       64         eMMC  NaN    14.1    No       383.61  
1482  Intel Celeron    6      128          SSD  NaN    14.1    No       317.02  
1483  Intel Celeron    6      128         eMMC  NaN    14.1    No       431.38

In [9]:
# Selecting only columns RAM, Storage, Screen.
selected_columns = data[['RAM', 'Storage', 'Screen']]
selected_columns

RAM  Storage  Screen
0       8      512    15.6
1       8      256    15.6
2       8      256    15.6
3      16     1000    15.6
4      16      512    15.6
...   ...      ...     ...
2155   16     1000    17.3
2156   16     1000    17.3
2157   32     1000    17.3
2158   16     1000    13.4
2159   16      256    13.4

[2160 rows x 3 columns]

In [10]:
# Getting the underlying NumPy array. Let's call it X.
import numpy as np
X = np.array([[5, 4, 7, 9, 11, 21], 
              [30, 21, 2, 5, 7, 12], [2, 5, 21, 9, 11, 7], 
             [5, 3, 2, 4, 2, 1], [23, 11, 21, 7, 5, 13], 
             [21, 11, 9, 7, 4, 5]])

# Computing matrix-matrix multiplication
X_transpose = X.T
result = np.dot(X_transpose, X)
result

array([[1924, 1159,  819,  541,  496,  888],
       [1159,  733,  511,  352,  351,  572],
       [ 819,  511, 1020,  480,  467,  638],
       [ 541,  352,  480,  301,  304,  442],
       [ 496,  351,  467,  304,  336,  479],
       [ 888,  572,  638,  442,  479,  829]])

In [11]:
# Inverse
inverse = np.linalg.inv(result)
inverse

array([[ 0.74917007, -1.16477992, -0.08672701, -0.81748724,  1.43412674,
        -0.32484249],
       [-1.16477992,  1.81439614,  0.13534363,  1.26573942, -2.22743679,
         0.50377098],
       [-0.08672701,  0.13534363,  0.01449345,  0.08369072, -0.16460808,
         0.03884944],
       [-0.81748724,  1.26573942,  0.08369072,  0.96300517, -1.60315551,
         0.35077713],
       [ 1.43412674, -2.22743679, -0.16460808, -1.60315551,  2.79046809,
        -0.63019327],
       [-0.32484249,  0.50377098,  0.03884944,  0.35077713, -0.63019327,
         0.14877716]])

In [12]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])
y

array([1100, 1300,  800,  900, 1000, 1100])

In [13]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w
w = np.dot(inverse, X_transpose) * y
total = w.sum()
total

213.18431521122244